function save() {
    localStorage.setItem("1", population);
    localStorage.setItem("2", populationMax);
    localStorage.setItem("3", food);
    localStorage.setItem("4", material);
    localStorage.setItem("5", luxury);
    localStorage.setItem("6", science);
    localStorage.setItem("7", aether);
    localStorage.setItem("8", military);
    localStorage.setItem("9", villager);
    localStorage.setItem("10", hunter);
    localStorage.setItem("11", gatherer);
    localStorage.setItem("12", builder);
    localStorage.setItem("13", elder);
    localStorage.setItem("14", shaman);
    localStorage.setItem("15", farmer);
    localStorage.setItem("16", woodcutter);
    localStorage.setItem("17", collector);
    localStorage.setItem("18", healer);
    localStorage.setItem("19", caravan);
    localStorage.setItem("20", shepard);
    localStorage.setItem("21", archer);
    localStorage.setItem("22", wagon);
    localStorage.setItem("23", miner);
    localStorage.setItem("24", spearman);
    localStorage.setItem("25", fisherman);
    localStorage.setItem("26", sailor);
    localStorage.setItem("27", scholar);
    localStorage.setItem("28", prophet);
    localStorage.setItem("29", horseman);
    localStorage.setItem("30", bowman);
    localStorage.setItem("31", lumberjack);
    localStorage.setItem("32", philosopher);
    localStorage.setItem("33", merchant);
    localStorage.setItem("34", engineer);
    localStorage.setItem("35", swordsman);
    localStorage.setItem("36", priest);
    localStorage.setItem("37", mage);
    localStorage.setItem("38", pikeman);
    localStorage.setItem("39", blacksmith);
    localStorage.setItem("40", captain);
    localStorage.setItem("41", pirate);
    localStorage.setItem("42", highscholar);
    localStorage.setItem("43", archmage);
    localStorage.setItem("44", knight);
    localStorage.setItem("45", paladin);
    localStorage.setItem("46", crossbowman);
    localStorage.setItem("47", longswordsman);
    localStorage.setItem("48", navigator1);
    localStorage.setItem("49", banker);
    localStorage.setItem("50", musketman);
    localStorage.setItem("51", commodore);
    localStorage.setItem("52", economist);
    localStorage.setItem("53", lancer);
    localStorage.setItem("54", chemist);
    localStorage.setItem("55", alchemist);
    localStorage.setItem("56", explorer);
    localStorage.setItem("57", scientist);
    localStorage.setItem("58", wizard);
    localStorage.setItem("59", gatlinggun);
    localStorage.setItem("60", operator);
    localStorage.setItem("61", rifleman);
    localStorage.setItem("62", warmage);
    localStorage.setItem("63", cavalry);
    localStorage.setItem("64", herbalist);
    localStorage.setItem("65", techmage);
    localStorage.setItem("66", infantry);
    localStorage.setItem("67", pilot);
    localStorage.setItem("68", aetherpilot);
    localStorage.setItem("69", heavyinfantry);
    localStorage.setItem("70", machinegunner);
    localStorage.setItem("71", warwagon);
    localStorage.setItem("72", marine);
    localStorage.setItem("73", atomicmage);
    localStorage.setItem("74", academic);
    localStorage.setItem("75", advancedpilot);
    localStorage.setItem("76", tank);
    localStorage.setItem("77", creationmage);
    localStorage.setItem("78", astronaut);
    localStorage.setItem("79", programmer);
    localStorage.setItem("80", aethersoldier);
    localStorage.setItem("153", camp);
    localStorage.setItem("154", hut);
    localStorage.setItem("155", towncentre);
    localStorage.setItem("156", farm);
    localStorage.setItem("157", cottage);
    localStorage.setItem("158", mine);
    localStorage.setItem("159", granary);
    localStorage.setItem("160", totem);
    localStorage.setItem("161", livestock);
    localStorage.setItem("162", watermill);
    localStorage.setItem("163", barrack);
    localStorage.setItem("164", dock);
    localStorage.setItem("165", library);
    localStorage.setItem("166", altar);
    localStorage.setItem("167", plantation);
    localStorage.setItem("168", trap);
    localStorage.setItem("169", quarry);
    localStorage.setItem("170", stable);
    localStorage.setItem("171", arena);
    localStorage.setItem("172", lumbermill);
    localStorage.setItem("173", terracefarm);
    localStorage.setItem("174", lighthouse);
    localStorage.setItem("175", park);
    localStorage.setItem("176", temple);
    localStorage.setItem("177", theatre);
    localStorage.setItem("178", market);
    localStorage.setItem("179", house);
    localStorage.setItem("180", building);
    localStorage.setItem("181", skyscraper);
    localStorage.setItem("182", houseCost);
    localStorage.setItem("183", buildingCost);
    localStorage.setItem("184", skyscraperCost);
    localStorage.setItem("185", fort);
    localStorage.setItem("186", forge);
    localStorage.setItem("187", sanctuary);
    localStorage.setItem("188", garden);
    localStorage.setItem("189", tradingpost);
    localStorage.setItem("190", workshop);
    localStorage.setItem("191", harbor);
    localStorage.setItem("192", university);
    localStorage.setItem("193", mageacademy);
    localStorage.setItem("194", castle);
    localStorage.setItem("195", forthaven);
    localStorage.setItem("196", armory);
    localStorage.setItem("197", observatory);
    localStorage.setItem("198", arcanebattery);
    localStorage.setItem("199", concerthouse);
    localStorage.setItem("200", bank);
    localStorage.setItem("201", seaport);
    localStorage.setItem("202", windmill);
    localStorage.setItem("203", arsenal);
    localStorage.setItem("204", historicsite);
    localStorage.setItem("205", school);
    localStorage.setItem("206", factory);
    localStorage.setItem("207", oilwell);
    localStorage.setItem("208", hydroplant);
    localStorage.setItem("209", broadcasttower);
    localStorage.setItem("210", researchlab);
    localStorage.setItem("211", medicallab);
    localStorage.setItem("212", academy);
    localStorage.setItem("213", airport);
    localStorage.setItem("214", nuclearplant);
    localStorage.setItem("215", solarplant);
    localStorage.setItem("216", spaceshipfactory);
    localStorage.setItem("217", hawk9);
    localStorage.setItem("218", genesiscockpit);
    localStorage.setItem("219", hawkheavy);
    localStorage.setItem("220", genesisengine);
    localStorage.setItem("221", genesisstasis);
    localStorage.setItem("222", genesisclinic);
    localStorage.setItem("286", agriculture);
    localStorage.setItem("287", mining);
    localStorage.setItem("288", pottery);
    localStorage.setItem("289", archery);
    localStorage.setItem("290", animalhusbandry);
    localStorage.setItem("291", thewheel);
    localStorage.setItem("292", bronzework);
    localStorage.setItem("293", sailing);
    localStorage.setItem("294", writing);
    localStorage.setItem("295", calendar);
    localStorage.setItem("296", trapping);
    localStorage.setItem("297", masonry);
    localStorage.setItem("298", horseback);
    localStorage.setItem("299", construction);
    localStorage.setItem("300", optics);
    localStorage.setItem("301", mathematics);
    //localStorage.setItem("302", construction);
    localStorage.setItem("303", philosophy);
    localStorage.setItem("304", dramapoetry);
    localStorage.setItem("305", currency);
    localStorage.setItem("306", engineering);
    localStorage.setItem("307", ironworking);
    localStorage.setItem("308", theology);
    localStorage.setItem("309", civilservice);
    localStorage.setItem("310", guilds);
    localStorage.setItem("311", metalcasting);
    localStorage.setItem("312", compass);
    localStorage.setItem("313", education);
    localStorage.setItem("314", chivalry);
    localStorage.setItem("315", machinery);
    localStorage.setItem("316", physics);
    localStorage.setItem("317", steel);
    localStorage.setItem("318", astronomy);
    localStorage.setItem("319", acoustics);
    localStorage.setItem("320", banking);
    localStorage.setItem("321", printingpress);
    localStorage.setItem("322", gunpowder);
    localStorage.setItem("323", navigation);
    localStorage.setItem("324", arquitecture);
    localStorage.setItem("325", economics);
    localStorage.setItem("326", metallurgy);
    localStorage.setItem("327", chemistry);
    localStorage.setItem("328", archeology);
    localStorage.setItem("329", scientific);
    localStorage.setItem("330", industrialization);
    localStorage.setItem("331", rifling);
    localStorage.setItem("332", militaryscience);
    localStorage.setItem("333", fertilizer);
    localStorage.setItem("334", biology);
    localStorage.setItem("335", electricity);
    localStorage.setItem("336", steampower);
    localStorage.setItem("337", dynamite);
    localStorage.setItem("338", refrigeration);
    localStorage.setItem("339", radio);
    localStorage.setItem("340", replaceableparts);
    localStorage.setItem("341", flight);
    localStorage.setItem("342", railroad);
    localStorage.setItem("343", plastics);
    localStorage.setItem("344", eletronics);
    localStorage.setItem("345", ballistics);
    localStorage.setItem("346", combustion);
    localStorage.setItem("347", penicillin);
    localStorage.setItem("348", atomictheory);
    localStorage.setItem("349", radar);
    localStorage.setItem("350", combinedarms);
    localStorage.setItem("351", nuclearfission);
    localStorage.setItem("352", ecology);
    localStorage.setItem("353", rocketry);
    localStorage.setItem("354", computers);
    localStorage.setItem("355", telecom);
    localStorage.setItem("356", mobiletactics);
    localStorage.setItem("357", advancedballistics);
    localStorage.setItem("358", sattelites);
    localStorage.setItem("359", robotics);
    localStorage.setItem("360", lasers);
    localStorage.setItem("361", particlephysics);
    localStorage.setItem("362", nuclearfusion);
    localStorage.setItem("363", nanotech);
    localStorage.setItem("364", stealth);
    localStorage.setItem("365", genetic);
    
    localStorage.setItem("446", theinternet);
    localStorage.setItem("447", theinternetCost);
    localStorage.setItem("448", artemis);
    localStorage.setItem("449", zeus);
    localStorage.setItem("450", stonehenge);
    localStorage.setItem("451", greatlibrary);
    localStorage.setItem("452", mausoleum);
    localStorage.setItem("453", pyramids);
    localStorage.setItem("454", colossus);
    localStorage.setItem("455", greatlighthouse);
    localStorage.setItem("456", greatwall);
    localStorage.setItem("457", hanginggardens);
    localStorage.setItem("458", oracle);
    localStorage.setItem("459", parthenon);
    localStorage.setItem("460", petra);
    localStorage.setItem("461", terracota);
    localStorage.setItem("462", alhambra);
    localStorage.setItem("463", angkor);
    localStorage.setItem("464", borobudur);
    localStorage.setItem("465", chichenitza);
    localStorage.setItem("466", hagiasophia);
    localStorage.setItem("467", machupicchu);
    localStorage.setItem("468", notredame);
    localStorage.setItem("469", forbiddenpalace);
    localStorage.setItem("470", globetheatre);
    localStorage.setItem("471", himejicastle);
    localStorage.setItem("472", pisa);
    localStorage.setItem("473", porcelain);
    localStorage.setItem("474", redfort);
    localStorage.setItem("475", sistinechapel);
    localStorage.setItem("476", tajmahal);
    localStorage.setItem("477", ufizzi);
    localStorage.setItem("478", bigben);
    localStorage.setItem("479", brandenburg);
    localStorage.setItem("480", louvre);
    localStorage.setItem("481", broadway);
    localStorage.setItem("482", eiffel);
    localStorage.setItem("483", kremlin);
    localStorage.setItem("484", neuschwanstein);
    localStorage.setItem("485", prora);
    localStorage.setItem("486", statueofliberty);
    localStorage.setItem("487", greatfirewall);
    localStorage.setItem("488", sidney);
    localStorage.setItem("489", CNtower);
    localStorage.setItem("490", hubble);
    localStorage.setItem("491", internationalSS);
    localStorage.setItem("492", artemisCost);
    localStorage.setItem("493", zeusCost);
    localStorage.setItem("494", stonehengeCost);
    localStorage.setItem("495", greatlibraryCost);
    localStorage.setItem("496", mausoleumCost);
    localStorage.setItem("497", pyramidsCost);
    localStorage.setItem("498", colossusCost);
    localStorage.setItem("499", greatlighthouseCost);
    localStorage.setItem("500", greatwallCost);
    localStorage.setItem("501", hanginggardensCost);
    localStorage.setItem("502", oracleCost);
    localStorage.setItem("503", parthenonCost);
    localStorage.setItem("504", petraCost);
    localStorage.setItem("505", terracotaCost);
    localStorage.setItem("506", alhambraCost);
    localStorage.setItem("507", angkorCost);
    localStorage.setItem("508", borobudurCost);
    localStorage.setItem("509", chichenitzaCost);
    localStorage.setItem("510", hagiasophiaCost);
    localStorage.setItem("511", machupicchuCost);
    localStorage.setItem("512", notredameCost);
    localStorage.setItem("513", forbiddenpalaceCost);
    localStorage.setItem("514", globetheatreCost);
    localStorage.setItem("515", himejicastleCost);
    localStorage.setItem("516", pisaCost);
    localStorage.setItem("517", porcelainCost);
    localStorage.setItem("518", redfortCost);
    localStorage.setItem("519", sistinechapelCost);
    localStorage.setItem("520", tajmahalCost);
    localStorage.setItem("521", ufizziCost);
    localStorage.setItem("522", bigbenCost);
    localStorage.setItem("523", brandenburgCost);
    localStorage.setItem("524", louvreCost);
    localStorage.setItem("525", broadwayCost);
    localStorage.setItem("526", eiffelCost);
    localStorage.setItem("527", kremlinCost);
    localStorage.setItem("528", neuschwansteinCost);
    localStorage.setItem("529", proraCost);
    localStorage.setItem("530", statueoflibertyCost);
    localStorage.setItem("531", greatfirewallCost);
    localStorage.setItem("532", pentagonCost);
    localStorage.setItem("533", sidneyCost);
    localStorage.setItem("534", CNtowerCost);
    localStorage.setItem("535", hubbleCost);
    localStorage.setItem("536", internationalSSCost);
    localStorage.setItem("537", globalMultiplier);
    localStorage.setItem("538", workerMultiplier);
    localStorage.setItem("539", unitcostMultiplier);
    localStorage.setItem("540", landunitCostMultiplier);
    localStorage.setItem("541", mountedunitCostMultiplier);
    localStorage.setItem("542", waterunitCostMultiplier);
    localStorage.setItem("543", airunitCostMultiplier);
    localStorage.setItem("544", buildingcostMultiplier);
    localStorage.setItem("545", foodMultiplier);
    localStorage.setItem("546", materialMultiplier);
    localStorage.setItem("547", luxuryMultiplier);
    localStorage.setItem("548", populationMultiplier);
    localStorage.setItem("549", popuMaxMultiplier);
    localStorage.setItem("550", pentagon);
    localStorage.setItem("551", pentagonCost);
    localStorage.setItem("552", medicallabCost);
    localStorage.setItem("553", scienceMultiplier);
    
    localStorage.setItem("555", militaryMultiplier);
    
    localStorage.setItem("561", researchMultiplier);
    localStorage.setItem("562", clickMultiplier);
    localStorage.setItem("563", wonderMultiplier);
    localStorage.setItem("564", wonderCount);
    localStorage.setItem("565", researchCost);
    localStorage.setItem("566", militia);
}
 
function load() {
    population = parseFloat(localStorage.getItem("1"));
    populationMax = parseFloat(localStorage.getItem("2"));
    food = parseFloat(localStorage.getItem("3"));
    material = parseFloat(localStorage.getItem("4"));
    luxury = parseFloat(localStorage.getItem("5"));
    science = parseFloat(localStorage.getItem("6"));
    aether = parseFloat(localStorage.getItem("7"));
    military = parseFloat(localStorage.getItem("8"));
    villager = parseFloat(localStorage.getItem("9"));
    hunter = parseFloat(localStorage.getItem("10"));
    gatherer = parseFloat(localStorage.getItem("11"));
    builder = parseFloat(localStorage.getItem("12"));
    elder = parseFloat(localStorage.getItem("13"));
    shaman = parseFloat(localStorage.getItem("14"));
    farmer = parseFloat(localStorage.getItem("15"));
    woodcutter = parseFloat(localStorage.getItem("16"));
    collector = parseFloat(localStorage.getItem("17"));
    healer = parseFloat(localStorage.getItem("18"));
    caravan = parseFloat(localStorage.getItem("19"));
    shepard = parseFloat(localStorage.getItem("20"));
    archer = parseFloat(localStorage.getItem("21"));
    wagon = parseFloat(localStorage.getItem("22"));
    miner = parseFloat(localStorage.getItem("23"));
    spearman = parseFloat(localStorage.getItem("24"));
    fisherman = parseFloat(localStorage.getItem("25"));
    sailor = parseFloat(localStorage.getItem("26"));
    scholar = parseFloat(localStorage.getItem("27"));
    prophet = parseFloat(localStorage.getItem("28"));
    horseman = parseFloat(localStorage.getItem("29"));
    bowman = parseFloat(localStorage.getItem("30"));
    lumberjack = parseFloat(localStorage.getItem("31"));
    philosopher = parseFloat(localStorage.getItem("32"));
    merchant = parseFloat(localStorage.getItem("33"));
    engineer = parseFloat(localStorage.getItem("34"));
    swordsman = parseFloat(localStorage.getItem("35"));
    priest = parseFloat(localStorage.getItem("36"));
    mage = parseFloat(localStorage.getItem("37"));
    pikeman = parseFloat(localStorage.getItem("38"));
    blacksmith = parseFloat(localStorage.getItem("39"));
    captain = parseFloat(localStorage.getItem("40"));
    pirate = parseFloat(localStorage.getItem("41"));
    highscholar = parseFloat(localStorage.getItem("42"));
    archmage = parseFloat(localStorage.getItem("43"));
    knight = parseFloat(localStorage.getItem("44"));
    paladin = parseFloat(localStorage.getItem("45"));
    crossbowman = parseFloat(localStorage.getItem("46"));
    longswordsman = parseFloat(localStorage.getItem("47"));
    navigator1 = parseFloat(localStorage.getItem("48"));
    banker = parseFloat(localStorage.getItem("49"));
    musketman = parseFloat(localStorage.getItem("50"));
    commodore = parseFloat(localStorage.getItem("51"));
    economist = parseFloat(localStorage.getItem("52"));
    lancer = parseFloat(localStorage.getItem("53"));
    chemist = parseFloat(localStorage.getItem("54"));
    alchemist = parseFloat(localStorage.getItem("55"));
    explorer = parseFloat(localStorage.getItem("56"));
    scientist = parseFloat(localStorage.getItem("57"));
    wizard = parseFloat(localStorage.getItem("58"));
    gatlinggun = parseFloat(localStorage.getItem("59"));
    operator = parseFloat(localStorage.getItem("60"));
    rifleman = parseFloat(localStorage.getItem("61"));
    warmage = parseFloat(localStorage.getItem("62"));
    cavalry = parseFloat(localStorage.getItem("63"));
    herbalist = parseFloat(localStorage.getItem("64"));
    techmage = parseFloat(localStorage.getItem("65"));
    infantry = parseFloat(localStorage.getItem("66"));
    pilot = parseFloat(localStorage.getItem("67"));
    aetherpilot = parseFloat(localStorage.getItem("68"));
    heavyinfrantry = parseFloat(localStorage.getItem("69"));
    machinegunner = parseFloat(localStorage.getItem("70"));
    warwagon = parseFloat(localStorage.getItem("71"));
    marine = parseFloat(localStorage.getItem("72"));
    atomicmage = parseFloat(localStorage.getItem("73"));
    academic = parseFloat(localStorage.getItem("74"));
    advancedpilot = parseFloat(localStorage.getItem("75"));
    tank = parseFloat(localStorage.getItem("76"));
    creationmage = parseFloat(localStorage.getItem("77"));
    astronaut = parseFloat(localStorage.getItem("78"));
    programmer = parseFloat(localStorage.getItem("79"));
    aethersoldier = parseFloat(localStorage.getItem("80"));
    camp = parseFloat(localStorage.getItem("153"));
    hut = parseFloat(localStorage.getItem("154"));
    towncentre = parseFloat(localStorage.getItem("155"));
    farm = parseFloat(localStorage.getItem("156"));
    cottage = parseFloat(localStorage.getItem("157"));
    mine = parseFloat(localStorage.getItem("158"));
    granary = parseFloat(localStorage.getItem("159"));
    totem = parseFloat(localStorage.getItem("160"));
    livestock = parseFloat(localStorage.getItem("161"));
    watermill = parseFloat(localStorage.getItem("162"));
    barrack = parseFloat(localStorage.getItem("163"));
    dock = parseFloat(localStorage.getItem("164"));
    library = parseFloat(localStorage.getItem("165"));
    altar = parseFloat(localStorage.getItem("166"));
    plantation = parseFloat(localStorage.getItem("167"));
    trap = parseFloat(localStorage.getItem("168"));
    quarry = parseFloat(localStorage.getItem("169"));
    stable = parseFloat(localStorage.getItem("170"));
    arena = parseFloat(localStorage.getItem("171"));
    lumbermill = parseFloat(localStorage.getItem("172"));
    terracefarm = parseFloat(localStorage.getItem("173"));
    lighthouse = parseFloat(localStorage.getItem("174"));
    park = parseFloat(localStorage.getItem("175"));
    temple = parseFloat(localStorage.getItem("176"));
    theatre = parseFloat(localStorage.getItem("177"));
    market = parseFloat(localStorage.getItem("178"));
    house = parseFloat(localStorage.getItem("179"));
    building = parseFloat(localStorage.getItem("180"));
    skyscraper = parseFloat(localStorage.getItem("181"));
    houseCost = parseFloat(localStorage.getItem("182"));
    buildingCost = parseFloat(localStorage.getItem("183"));
    skyscraperCost = parseFloat(localStorage.getItem("184"));
    fort = parseFloat(localStorage.getItem("185"));
    forge = parseFloat(localStorage.getItem("186"));
    sanctuary = parseFloat(localStorage.getItem("187"));
    garden = parseFloat(localStorage.getItem("188"));
    tradingpost = parseFloat(localStorage.getItem("189"));
    workshop = parseFloat(localStorage.getItem("190"));
    harbor = parseFloat(localStorage.getItem("191"));
    university = parseFloat(localStorage.getItem("192"));
    mageacademy = parseFloat(localStorage.getItem("193"));
    castle = parseFloat(localStorage.getItem("194"));
    forthaven = parseFloat(localStorage.getItem("195"));
    armory = parseFloat(localStorage.getItem("196"));
    observatory = parseFloat(localStorage.getItem("197"));
    arcanebattery = parseFloat(localStorage.getItem("198"));
    concerthouse = parseFloat(localStorage.getItem("199"));
    bank = parseFloat(localStorage.getItem("200"));
    seaport = parseFloat(localStorage.getItem("201"));
    windmill = parseFloat(localStorage.getItem("202"));
    arsenal = parseFloat(localStorage.getItem("203"));
    historicsite = parseFloat(localStorage.getItem("204"));
    school = parseFloat(localStorage.getItem("205"));
    factory = parseFloat(localStorage.getItem("206"));
    oilwell = parseFloat(localStorage.getItem("207"));
    hydroplant = parseFloat(localStorage.getItem("208"));
    broadcasttower = parseFloat(localStorage.getItem("209"));
    researchlab = parseFloat(localStorage.getItem("210"));
    medicallab = parseFloat(localStorage.getItem("211"));
    academy = parseFloat(localStorage.getItem("212"));
    airport = parseFloat(localStorage.getItem("213"));
    nuclearplant = parseFloat(localStorage.getItem("214"));
    solarplant = parseFloat(localStorage.getItem("215"));
    spaceshipfactory = parseFloat(localStorage.getItem("216"));
    hawk9 = parseFloat(localStorage.getItem("217"));
    genesiscockpit = parseFloat(localStorage.getItem("218"));
    hawkheavy = parseFloat(localStorage.getItem("219"));
    genesisengine = parseFloat(localStorage.getItem("220"));
    genesisstasis = parseFloat(localStorage.getItem("221"));
    genesisclinic = parseFloat(localStorage.getItem("222"));
    agriculture = parseFloat(localStorage.getItem("286"));
    mining = parseFloat(localStorage.getItem("287"));
    pottery = parseFloat(localStorage.getItem("288"));
    archery = parseFloat(localStorage.getItem("289"));
    animalhusbandry = parseFloat(localStorage.getItem("290"));
    thewheel = parseFloat(localStorage.getItem("291"));
    bronzework = parseFloat(localStorage.getItem("292"));
    sailing = parseFloat(localStorage.getItem("293"));
    writing = parseFloat(localStorage.getItem("294"));
    calendar = parseFloat(localStorage.getItem("295"));
    trapping = parseFloat(localStorage.getItem("296"));
    masonry = parseFloat(localStorage.getItem("297"));
    horseback = parseFloat(localStorage.getItem("298"));
    construction = parseFloat(localStorage.getItem("299"));
    optics = parseFloat(localStorage.getItem("300"));
    mathematics = parseFloat(localStorage.getItem("301"));
    //construction = localStorage.getItem("302");
    philosophy = parseFloat(localStorage.getItem("303"));
    dramapoetry = parseFloat(localStorage.getItem("304"));
    currency = parseFloat(localStorage.getItem("305"));
    engineering = parseFloat(localStorage.getItem("306"));
    ironworking = parseFloat(localStorage.getItem("307"));
    theology = parseFloat(localStorage.getItem("308"));
    civilservice = parseFloat(localStorage.getItem("309"));
    guilds = parseFloat(localStorage.getItem("310"));
    metalcasting = parseFloat(localStorage.getItem("311"));
    compass = parseFloat(localStorage.getItem("312"));
    education = parseFloat(localStorage.getItem("313"));
    chivalry = parseFloat(localStorage.getItem("314"));
    machinery = parseFloat(localStorage.getItem("315"));
    physics = parseFloat(localStorage.getItem("316"));
    steel = parseFloat(localStorage.getItem("317"));
    astronomy = parseFloat(localStorage.getItem("318"));
    acoustics = parseFloat(localStorage.getItem("319"));
    banking = parseFloat(localStorage.getItem("320"));
    printingpress = parseFloat(localStorage.getItem("321"));
    gunpowder = parseFloat(localStorage.getItem("322"));
    navigation = parseFloat(localStorage.getItem("323"));
    arquitecture = parseFloat(localStorage.getItem("324"));
    economics = parseFloat(localStorage.getItem("325"));
    metallurgy = parseFloat(localStorage.getItem("326"));
    chemistry = parseFloat(localStorage.getItem("327"));
    archeology = parseFloat(localStorage.getItem("328"));
    scientific = parseFloat(localStorage.getItem("329"));
    industrialization = parseFloat(localStorage.getItem("330"));
    rifling = parseFloat(localStorage.getItem("331"));
    militaryscience = parseFloat(localStorage.getItem("332"));
    fertilizer = parseFloat(localStorage.getItem("333"));
    biology = parseFloat(localStorage.getItem("334"));
    electricity = parseFloat(localStorage.getItem("335"));
    steampower = parseFloat(localStorage.getItem("336"));
    dynamite = parseFloat(localStorage.getItem("337"));
    refrigeration = parseFloat(localStorage.getItem("338"));
    radio = parseFloat(localStorage.getItem("339"));
    replaceableparts = parseFloat(localStorage.getItem("340"));
    flight = parseFloat(localStorage.getItem("341"));
    railroad = parseFloat(localStorage.getItem("342"));
    plastics = parseFloat(localStorage.getItem("343"));
    eletronics = parseFloat(localStorage.getItem("344"));
    ballistics = parseFloat(localStorage.getItem("345"));
    combustion = parseFloat(localStorage.getItem("346"));
    penicillin = parseFloat(localStorage.getItem("347"));
    atomictheory = parseFloat(localStorage.getItem("348"));
    radar = parseFloat(localStorage.getItem("349"));
    combinedarms = parseFloat(localStorage.getItem("350"));
    nuclearfission = parseFloat(localStorage.getItem("351"));
    ecology = parseFloat(localStorage.getItem("352"));
    rocketry = parseFloat(localStorage.getItem("353"));
    computers = parseFloat(localStorage.getItem("354"));
    telecom = parseFloat(localStorage.getItem("355"));
    mobiletactics = parseFloat(localStorage.getItem("356"));
    advancedballistics = parseFloat(localStorage.getItem("357"));
    sattelites = parseFloat(localStorage.getItem("358"));
    robotics = parseFloat(localStorage.getItem("359"));
    lasers = parseFloat(localStorage.getItem("360"));
    particlephysics = parseFloat(localStorage.getItem("361"));
    nuclearfusion = parseFloat(localStorage.getItem("362"));
    nanotech = parseFloat(localStorage.getItem("363"));
    stealth = parseFloat(localStorage.getItem("364"));
    genetic = parseFloat(localStorage.getItem("365"));
    
    theinternet = parseFloat(localStorage.getItem("446"));
    theinternetCost = parseFloat(localStorage.getItem("447"));
    artemis = parseFloat(localStorage.getItem("448"));
    zeus = parseFloat(localStorage.getItem("449"));
    stonehenge = parseFloat(localStorage.getItem("450"));
    greatlibrary = parseFloat(localStorage.getItem("451"));
    mausoleum = parseFloat(localStorage.getItem("452"));
    pyramids = parseFloat(localStorage.getItem("453"));
    colossus = parseFloat(localStorage.getItem("454"));
    greatlighthouse = parseFloat(localStorage.getItem("455"));
    greatwall = parseFloat(localStorage.getItem("456"));
    hanginggardens = parseFloat(localStorage.getItem("457"));
    oracle = parseFloat(localStorage.getItem("458"));
    parthenon = parseFloat(localStorage.getItem("459"));
    petra = parseFloat(localStorage.getItem("460"));
    terracota = parseFloat(localStorage.getItem("461"));
    alhambra = parseFloat(localStorage.getItem("462"));
    angkor = parseFloat(localStorage.getItem("463"));
    borobudur = parseFloat(localStorage.getItem("464"));
    chichenitza = parseFloat(localStorage.getItem("465"));
    hagiasophia = parseFloat(localStorage.getItem("466"));
    machupicchu = parseFloat(localStorage.getItem("467"));
    notredame = parseFloat(localStorage.getItem("468"));
    forbiddenpalace = parseFloat(localStorage.getItem("469"));
    globetheatre = parseFloat(localStorage.getItem("470"));
    himejicastle = parseFloat(localStorage.getItem("471"));
    pisa = parseFloat(localStorage.getItem("472"));
    porcelain = parseFloat(localStorage.getItem("473"));
    redfort = parseFloat(localStorage.getItem("474"));
    sistinechapel = parseFloat(localStorage.getItem("475"));
    tajmahal = parseFloat(localStorage.getItem("476"));
    ufizzi = parseFloat(localStorage.getItem("477"));
    bigben = parseFloat(localStorage.getItem("478"));
    brandenburg = parseFloat(localStorage.getItem("479"));
    louvre = parseFloat(localStorage.getItem("480"));
    broadway = parseFloat(localStorage.getItem("481"));
    eiffel = parseFloat(localStorage.getItem("482"));
    kremlin = parseFloat(localStorage.getItem("483"));
    neuschwanstein = parseFloat(localStorage.getItem("484"));
    prora = parseFloat(localStorage.getItem("485"));
    statueofliberty = parseFloat(localStorage.getItem("486"));
    greatfirewall = parseFloat(localStorage.getItem("487"));
    sidney = parseFloat(localStorage.getItem("488"));
    CNtower = parseFloat(localStorage.getItem("489"));
    hubble = parseFloat(localStorage.getItem("490"));
    internationalSS = parseFloat(localStorage.getItem("491"));
    artemisCost = parseFloat(localStorage.getItem("492"));
    zeusCost = parseFloat(localStorage.getItem("493"));
    stonehengeCost = parseFloat(localStorage.getItem("494"));
    greatlibraryCost = parseFloat(localStorage.getItem("495"));
    mausoleumCost = parseFloat(localStorage.getItem("496"));
    pyramidsCost = parseFloat(localStorage.getItem("497"));
    colossusCost = parseFloat(localStorage.getItem("498"));
    greatlighthouseCost = parseFloat(localStorage.getItem("499"));
    greatwallCost = parseFloat(localStorage.getItem("500"));
    hanginggardensCost = parseFloat(localStorage.getItem("501"));
    oracleCost = parseFloat(localStorage.getItem("502"));
    parthenonCost = parseFloat(localStorage.getItem("503"));
    petraCost = parseFloat(localStorage.getItem("504"));
    terracotaCost = parseFloat(localStorage.getItem("505"));
    alhambraCost = parseFloat(localStorage.getItem("506"));
    angkorCost = parseFloat(localStorage.getItem("507"));
    borobudurCost = parseFloat(localStorage.getItem("508"));
    chichenitzaCost = parseFloat(localStorage.getItem("509"));
    hagiasophiaCost = parseFloat(localStorage.getItem("510"));
    machupicchuCost = parseFloat(localStorage.getItem("511"));
    notredameCost = parseFloat(localStorage.getItem("512"));
    forbiddenpalaceCost = parseFloat(localStorage.getItem("513"));
    globetheatreCost = parseFloat(localStorage.getItem("514"));
    himejicastleCost = parseFloat(localStorage.getItem("515"));
    pisaCost = parseFloat(localStorage.getItem("516"));
    porcelainCost = parseFloat(localStorage.getItem("517"));
    redfortCost = parseFloat(localStorage.getItem("518"));
    sistinechapelCost = parseFloat(localStorage.getItem("519"));
    tajmahalCost = parseFloat(localStorage.getItem("520"));
    ufizziCost = parseFloat(localStorage.getItem("521"));
    bigbenCost = parseFloat(localStorage.getItem("522"));
    brandenburgCost = parseFloat(localStorage.getItem("523"));
    louvreCost = parseFloat(localStorage.getItem("524"));
    broadwayCost = parseFloat(localStorage.getItem("525"));
    eiffelCost = parseFloat(localStorage.getItem("526"));
    kremlinCost = parseFloat(localStorage.getItem("527"));
    neuschwansteinCost = parseFloat(localStorage.getItem("528"));
    proraCost = parseFloat(localStorage.getItem("529"));
    statueoflibertyCost = parseFloat(localStorage.getItem("530"));
    greatfirewallCost = parseFloat(localStorage.getItem("531"));
    pentagonCost = parseFloat(localStorage.getItem("532"));
    sidneyCost = parseFloat(localStorage.getItem("533"));
    CNtowerCost = parseFloat(localStorage.getItem("534"));
    hubbleCost = parseFloat(localStorage.getItem("535"));
    internationalSSCost = parseFloat(localStorage.getItem("536"));
    globalMultiplier = parseFloat(localStorage.getItem("537"));
    workerMultiplier = parseFloat(localStorage.getItem("538"));
    unitcostMultiplier = parseFloat(localStorage.getItem("539"));
    landunitCostMultiplier = parseFloat(localStorage.getItem("540"));
    mountedunitCostMultiplier = parseFloat(localStorage.getItem("541"));
    waterunitCostMultiplier = parseFloat(localStorage.getItem("542"));
    airunitCostMultiplier = parseFloat(localStorage.getItem("543"));
    buildingcostMultiplier = parseFloat(localStorage.getItem("544"));
    foodMultiplier = parseFloat(localStorage.getItem("545"));
    materialMultiplier = parseFloat(localStorage.getItem("546"));
    luxuryMultiplier = parseFloat(localStorage.getItem("547"));
    populationMultiplier = parseFloat(localStorage.getItem("548"));
    popuMaxMultiplier = parseFloat(localStorage.getItem("549"));
    pentagon = parseFloat(localStorage.getItem("550"));
    //localStorage.getItem("551");
    //localStorage.getItem("552");
    scienceMultiplier = parseFloat(localStorage.getItem("553"));

    militaryMultiplier = parseFloat(localStorage.getItem("555"));
    
    researchMultiplier = parseFloat(localStorage.getItem("561"));
    clickMultiplier = parseFloat(localStorage.getItem("562"));
    wonderMultiplier = parseFloat(localStorage.getItem("563"));
    wonderCount = parseFloat(localStorage.getItem("564"));
    researchCost = parseFloat(localStorage.getItem("565"));
    militia = parseFloat(localStorage.getItem("566"));
    update()
}